version: 3.0.{build}-{branch}
image: Visual Studio 2017
clone_depth: 1

matrix:
  fast_finish: true

nuget:
  disable_publish_on_pr: true

environment:
  CODECOV_TOKEN:
    secure: qGOrjom/Itd2Mu4kw0IEnwPzr43pBTTt3JUZGSLYvP+FZP0ssORhvp0nOn+3MQIM

before_build:
- choco install opencover.portable
- choco install codecov

build_script:
- dotnet --info
- dotnet restore --no-cache
- dotnet build --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER% --no-restore

test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\tests\BestClipOfTheWeek.Tests.Unit\bin\Release\netcoreapp2.1\BestClipOfTheWeek.Tests.Unit.dll -noshadow" -filter:"+[BestClipOfTheWeek*]* -[BestClipOfTheWeek.Tests.Unit*]*" -output:".\coverage.xml" -hideskipped:File -mergebyhash -skipautoprops -threshold:9999
- codecov -f ".\coverage.xml"

artifacts:
  - path: Artifacts\x64
    name: Setup_x64
    type: zip
  - path: Artifacts\x86
    name: Setup_x86
    type: zip

deploy:
  release: Best Clip of the Week v$(appveyor_build_version)
  description: 'Appveyor auto-generated release'
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: zQGJD6fs/xhZgf/3Rkagg765kNLqIsJ9ouxG/XUNknwalfz/jb8wp7+ZpTRzYhEp
  artifact: Setup_x64,Setup_x86
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
