version: 3.0.{build}-{branch}
image: Visual Studio 2017
clone_depth: 1

matrix:
  fast_finish: true

nuget:
  disable_publish_on_pr: true

environment:
  CODECOV_TOKEN:
    secure: qGOrjom/Itd2Mu4kw0IEnwPzr43pBTTt3JUZGSLYvP+FZP0ssORhvp0nOn+3MQIM

before_build:
- choco install codecov
- dotnet --version
- dotnet --info
- dotnet tool install --global coverlet.console
- dotnet restore ./src/BestClipOfTheWeek/BestClipOfTheWeek.csproj --verbosity m --no-cache

build_script:
- dotnet build ./src/BestClipOfTheWeek/BestClipOfTheWeek.csproj -c Release --version-suffix %APPVEYOR_BUILD_NUMBER% --no-restore
- dotnet publish ./src/BestClipOfTheWeek/BestClipOfTheWeek.csproj -c Release --no-build --no-restore

test_script:
- dotnet restore ./tests/BestClipOfTheWeek.Tests.Unit/BestClipOfTheWeek.Tests.Unit.csproj --verbosity m --no-cache
- dotnet build ./tests/BestClipOfTheWeek.Tests.Unit/BestClipOfTheWeek.Tests.Unit.csproj -c Release --no-restore
- coverlet tests/BestClipOfTheWeek.Tests.Unit/bin/Release/netcoreapp2.1/BestClipOfTheWeek.Tests.Unit.dll --target "dotnet" --targetargs "test tests/BestClipOfTheWeek.Tests.Unit/BestClipOfTheWeek.Tests.Unit.csproj -c Release --no-build" --format opencover
- codecov -f coverage.opencover.xml

artifacts:
 - path: '\src\BestClipOfTheWeek\bin\Release\netcoreapp2.1\publish'
   name: WebSite
   type: WebDeployPackage

deploy:
- provider: AzureAppServiceZipDeploy
  website: BestClipOfTheWeek
  username: justinprobb
  password:
    secure: 6FXUUPKgWuCGiuhoGRi0596iM2tmDjffVkfDgl0Tg1UBCzfqhRRjNJHbtKssPKYQ
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
