name: Test

on:
  pull_request:
    branches: [master]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.0-preview.5.21301.17

      - name: Test
        run: dotnet test -v n -c Release --collect:"XPlat Code Coverage"

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
